
title: Andrew Towner
email: keytonic@gmail.com
#description: >- # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: drootown
github_username: keytonic
facebook_username: keytonic
instagram_username: drootown
linkedin_username: townera
strava: 1645425
website_url: https://www.andrewtowner.com
theme: minima
#plugins:
#  - jekyll-feed
plugins: [jekyll-paginate]

show_excerpts: true
excerpt_separator: <!-- excerpt-end -->

#gems: [jekyll-paginate]
paginate: 6
paginate_path: "/page:num/"



header_pages:
  - about.markdown
  - contact.markdown
  - index.html